microsoft/PSDocs

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Added GitHub issue templates for bug report and feature request.

Added GitHub templates

---

src/PSDocs/PSDocsProcessor/Markdown/Markdown.psm1
tests/PSDocs.Tests/PSDocs.Section.Tests.ps1
tests/PSDocs.Tests/PSDocs.Table.Tests.ps1

- Fix string processing issue due to wrapping not limited to tables #11
- Added line break after table
Fix #11

Fix line wrap occurring for all new lines issue #11

---

scripts/vstsbuild.ps1

Added build scripts for bootstrapping release with VSTS.

Added bootstrap build script for VSTS

---

PSDocs.build.ps1

Fixes for release process in VSTS.

Updated to fix release module version for VSTS

---

CHANGELOG.md
README.md
docs/keywords/PSDocs/en-US/about_PSDocs_Keywords.md

- Fix broken links when browsing GitHub pages
- Update to change log to mark encoding change as breaking instead of only important

Updates to documentation and links

---

CHANGELOG.md
docs/keywords/PSDocs/en-US/about_PSDocs_Keywords.md
src/PSDocs/PSDocs.psm1
tests/PSDocs.Tests/PSDocs.Table.Tests.ps1

- Added property expressions to `Table` keyword
- Fixed output error displaying string builder object in `Invoke-PSDocument` output
Fix #27

Added table property expressions #27 and fix output error

---

ThirdPartyNotices.txt

Added notice for YamlDotNet package.

Added YamlDotNet notice

---

CHANGELOG.md
PSDocs.build.ps1
appveyor.yml
src/PSDocs/PSDocsProcessor/Markdown/Markdown.psm1

- Updated change log and minor formatting for release

Updates for v0.5.0 release

---

README.md
src/PSDocs.Dsc/PSDocs.Dsc.psd1
src/PSDocs/PSDocs.psd1

- Updated module publisher information and description to more clearly articulate that the PSDocs, PSDocs.Dsc modules are not a supported product.

Fix module publisher

---

CHANGELOG.md
README.md
docs/keywords/PSDocs/en-US/about_PSDocs_Keywords.md
src/PSDocs/Models/BlockQuote.cs
src/PSDocs/Models/DocumentNodeType.cs
src/PSDocs/Models/ModelHelper.cs
src/PSDocs/PSDocs.psd1
src/PSDocs/PSDocs.psm1
src/PSDocs/Processor/Markdown/MarkdownProcessor.cs
tests/PSDocs.Tests/PSDocs.BlockQuote.Tests.ps1
tests/PSDocs.Tests/PSDocs.Note.Tests.ps1
tests/PSDocs.Tests/PSDocs.Warning.Tests.ps1
tests/PSDocs.Tests/WithError.doc.ps1

- Added `BlockQuote` keyword
- Updated Note and Warning keywords to support pipeline input

Added support for block quote

---

azure-pipelines.yml

- Filter CI trigger to only build master

Add CI trigger branch filter

---

CHANGELOG.md
src/PSDocs/Processor/Markdown/MarkdownProcessor.cs
tests/PSDocs.Tests/PSDocs.Table.Tests.ps1

- Fix null reference for table columns with undefined properties #53 
Fixes #53

Fix null reference for table columns with undefined properties #53

---

CHANGELOG.md

- Update change log for v0.6.1 release

Updates for v0.6.1 release

---

PSDocs.build.ps1

- Publish-Module required out to be added to PSModulePath to resolve RequiredModules

Fix Publish-Module with RequiredModules

---

docs/scenarios/arm-template/arm-template.doc.ps1
docs/scenarios/arm-template/arm-template.md
docs/scenarios/arm-template/output.md

- Update docs to use Az cmdlet instead of AzureRm cmdlets.

Update AzureRm cmdlet names

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md

- Add PR template and CODEOWNERS files.

Add PR template and CODEOWNERS

---

CHANGELOG.md
src/PSDocs/PSDocs.psm1
tests/PSDocs.Tests/PSDocs.Code.Tests.ps1

- Fix concatenation of multiple lines in Code section. #69
Fixes #69 

Fix concatenation of Code section #69

---

CHANGELOG.md

- Fix concatenation of multiple lines in Code section. #69

Release v0.6.3

---

.azure-pipelines/azure-pipelines.yaml
.github/PULL_REQUEST_TEMPLATE.md
README.md
docs/commands/PSDocs/en-US/Document.md
docs/commands/PSDocs/en-US/Get-PSDocumentHeader.md
docs/commands/PSDocs/en-US/Invoke-PSDocument.md
docs/commands/PSDocs/en-US/New-PSDocumentOption.md
docs/concepts/PSDocs/en-US/about_PSDocs_Options.md
docs/concepts/PSDocs/en-US/about_PSDocs_Variables.md
docs/keywords/PSDocs/en-US/about_PSDocs_Keywords.md
src/PSDocs/PSDocs.csproj
src/PSDocs/PSDocs.psd1

- Renamed default branch to main.

Rename default branch to main

---

.github/dependabot.yml
CHANGELOG.md
ThirdPartyNotices.txt
pipeline.build.ps1
src/PSDocs/PSDocs.csproj

- Bump YamlDotNet dependency to v8.1.2.

Bump YamlDotNet to v8.1.2

---

CHANGELOG.md
README.md
docs/install-instructions.md
docs/upgrade-notes.md

- Added information for upgading between versions.

Added upgrade information links

---

.vscode/settings.json
CHANGELOG.md
docs/upgrade-notes.md

- Added upgrade notes for helper function scope requirement to be flagged as global.

Add notes on helper function scope

---

CHANGELOG.md

What's changed since pre-release v0.7.0-B2008022:
- Added support for using document definitions from modules. #81

Pre-release v0.7.0-B2008022

---

docs/commands/PSDocs/en-US/Invoke-PSDocument.md

Added example to Invoke-PSDocument command help to demonstrate the use of InputObject

Added example of InputObject to help

---

.azure-pipelines/azure-pipelines.yaml
.github/dependabot.yml
tests/PSDocs.Tests/PSDocs.Common.Tests.ps1

- Ignore upgrade of PS 7.1 in tool chain.
- Updated CI pipeline to test against GA PS 7.1.

Update CI for PS 7.1

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

- Updated GitHub issue templates and added question template.

Updated GitHub issue templates

---

CHANGELOG.md
src/PSDocs/Processor/Markdown/MarkdownProcessor.cs
tests/PSDocs.Tests/FromFile.Keyword.Doc.ps1
tests/PSDocs.Tests/PSDocs.BlockQuote.Tests.ps1

- Fixed line break after block quote. #104
Fixes #104 

Fixed line break after block quote #104

---

README.md
docs/scenarios/arm-template/arm-template.Doc.ps1
docs/scenarios/arm-template/arm-template.md
docs/scenarios/directory/directory.md
docs/upgrade-notes.md

- Minor doc improvements and fixes.

Minor docs improvements and fixes

---

CHANGELOG.md

What's changed since pre-release v0.7.0-B2008035:
- Added support for localized strings using the `$LocalizedData` variable. #91
- Automatically serialize `Code` objects to JSON and YAML. #93
- Use the `json`, `yaml`, or `yml` info strings to automatically serialize custom objects.
- See `about_PSDocs_Keywords` for more details.
- Added configuration for setting output options. #105
- Added parameter alias `-MarkdownEncoding` on `New-PSDocumentOption` for `-Encoding`. #106
- Default the info string to `powershell` for `Code` script blocks. #92
- See `about_PSDocs_Keywords` for more details.
- Bug fixes:
- Fixed inconsistencies with default options file name. #103
- Fixed line break after block quote. #104

Pre-release v0.7.0-B2101015

---

docs/scenarios/arm-template/arm-template.md

Added optional parameters to both PowerShell and CLI samples to allow ARM template parameters to be passed in.
* PowerShell -TemplateParameterFile and 
* CLI --parameters @<path-to-templateparameterfile>

Added an optional parameter

---

.azure-pipelines/azure-pipelines.yaml

- Update CI pipeline version after release.

Bump pipeline version to v0.8.0

---

CHANGELOG.md

What's changed since v0.7.0:
- Added support for custom configuration key values. #121
- See `about_PSDocs_Configuration` for more details.
- Improve handling when an empty document title is set. #122
- Bug fixes:
- Fixed use of error action preference with `Include` keyword. #127

Pre-release v0.8.0-B2101006

---

CHANGELOG.md

What's changed since pre-release v0.8.0-B2101006:
- Added `-Replace` parameter to `Include` keyword to replace tokens in included file. #134
- A hashtable of replacement tokens can be specified to replace contents within original file.
- See `about_PSDocs_Keywords` for more details.

Pre-release v0.8.0-B2101011

---

src/PSDocs/Commands/IncludeCommand.cs
src/PSDocs/Commands/SectionCommand.cs
src/PSDocs/Configuration/PSDocumentOption.cs
src/PSDocs/Models/SectionNode.cs
src/PSDocs/Models/TableBuilder.cs
src/PSDocs/Pipeline/GetPipeline.cs
src/PSDocs/Pipeline/PipelineContext.cs
src/PSDocs/Pipeline/PipelineStream.cs
src/PSDocs/Pipeline/StreamPipeline.cs
src/PSDocs/Resources/PSDocsResources.Designer.cs
src/PSDocs/Resources/PSDocsResources.resx
src/PSDocs/Runtime/RunspaceContext.cs

- Code quality update. No functional changes.

Code quality updates

---

src/PSDocs/Commands/IncludeCommand.cs

- Code quality improvements. No functional changes.

Code quality improvement

---

CHANGELOG.md

What's changed since pre-release v0.8.0-B2101011:
- Added support for running custom actions using conventions. #18
#120
- Conventions provide `Begin`, `Process` and `End` blocks to hook into the document pipeline.
- Name or change the output path of documents in `Begin` and `Process` blocks.
- Generate table of contents (TOC) and perform publishing actions in `End` blocks.
- Bug fixes:
- Fixed boolean string conversion with the `GetBoolOrDefault` configuration helper. [#140](https://github.com/BernieWhite/PSDocs/issues/140)

Pre-release v0.8.0-B2102012

---

CHANGELOG.md

What's changed since v0.8.0:
- Added support for document data and metadata in `end` convention blocks. #148

Pre-release v0.9.0-B2102002

---

CHANGELOG.md

- Updated change log for YamlDotNet version.

Bump YamlDotNet version in change log

---

CHANGELOG.md

What's changed since pre-release v0.9.0-B2106004:
- Engineering:
- Migrated PSDocs to Microsoft GitHub organization. #145
- Bump YamlDotNet dependency to v11.2.1. #168

Pre-release v0.9.0-B2107002

---

CHANGELOG.md

What's changed since pre-release v0.9.0-B2107002:
- Added support for reading objects from file. #132 #131
- Added support for conditionally processing documents based on target object. #133
- **Breaking change**: Documents that do not set a body are skipped.
- Conditionally process target objects with script block or selector based conditions.
- Script block based conditions are PowerShell code that can be added to `Document` blocks with `-If`.
- Selector block based conditions are YAML filters that can be added to `Document` blocks with `-With`.
- Added options for configuring processing of input.
- Added schema for PSDocs configuration options within `ps-docs.yaml`. #113

Pre-release v0.9.0-B2107010

---

CHANGELOG.md

What's changed since pre-release v0.9.0-B2107015:
- Added string selector conditions. #178
- Use `startWith`, `contains`, and `endsWith` to check for a sub-string.
- Use `isString`, `isLower`, and `isUpper` to check for string type and casing.
- See [about_PSDocs_Selectors] and [about_PSDocs_Options] for more details.

Pre-release v0.9.0-B2107020

---

.azure-pipelines/azure-pipelines.yaml
.github/ISSUE_TEMPLATE/bug_report.md

Bump CI pipeline

---

.azure-pipelines/azure-pipelines.yaml

- Removed PS 6.x test container.
- Updated ubuntu and PS versions.
- Added alpine image.

Update CI pipeline agents

---

.azure-pipelines/azure-pipelines.yaml
.azure-pipelines/jobs/testContainer.yaml

Update CI images

---

CHANGELOG.md
README.md

This pull request includes a small change to the `README.md` file. The change adds Vic Perdana as a maintainer.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R200): Added Vic Perdana to the list of maintainers.

chore: Update Maintainer
